version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # For main webapp
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
